apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: content
        image: bash
        command:
        - bash
        - -c
        - |
          cat >/usr/share/nginx/html/index.html <<EOF
          <html>
            <body bgcolor="{{ .Values.backgroud }}">
              <h1>{{ .Values.title }}</h1>
              <h2>Content:{{ .Values.content }}</h2>
            </body>
          </html>
          EOF
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
