apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    name: http
    nodePort: {{ .Values.nodePort }}
  selector:
    app: nginx
